[package]
name = "mochi_os"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

build-std = ["core", "compiler_builtins"]
[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

